### ISSUE TITLE
Should we disable retry on POST/PUT methods?

### ISSUE THREAD

**Issue by aliel** [aleph-im/aleph-proxy#13]
regarding these => 
https://github.com/aleph-im/aleph-proxy/blob/main/aleph_proxy_config/config.yaml#L50
https://github.com/aleph-im/aleph-proxy/blob/main/aleph_proxy_config/config.yaml#L57
```
to-aleph-vm:  # Forward VM calls to all available Compute Resource Nodes in the network
  rule: "PathPrefix(`/vm/`)"
  service: aleph-vm
  middlewares:
    - retry-if-no-reply
...
  middlewares:
    retry-if-no-reply:
      retry:
        attempts: 4
        initialInterval: 5ms
```

as we know, it is almost never safe to retry a request that alters a state
